# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SoftwareTesting_TopUp' do

pod 'MBProgressHUD', '~> 0.9.2'
pod 'SwiftCSV'

end

target 'SoftwareTesting_TopUpTests' do

end

target 'SoftwareTesting_TopUpUITests' do

end

